name: Refresh

on:
  schedule:
    - cron: '30 */4 * * *' # every 4 hrs at minute 30
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Trigger GitHub pages rebuild
        # https://docs.github.com/en/rest/reference/repos#request-a-github-pages-build
        run: |
          curl \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Authorization: Bearer ${{ SECRET }}" \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds
